[package]
name = "nx"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }

[build-dependencies]
clap = { version = "4.5.32", features = ["derive"] }
clap_complete = "4.5.47"
