[package]
name = "nx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
clap_complete = "4.5.47"
dirs = "6.0.0"
ron = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
